### ISSUE TITLE
Correct Procedure to update version

### ISSUE THREAD

**Issue by gino8080** [zengxs/gitlab-arm64#142]
Please can you describe the steps to make a correct update procedure?

my docker-compose is like this

```
version: '3.6'
services:
  gitlab:
    image: 'zengxs/gitlab:latest'
    restart: always
    container_name: gitlab
    hostname: '*********.it'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'https://**********.it'

        gitlab_rails['gitlab_shell_ssh_port'] = 2222
        letsencrypt['enabled'] = false
        gitlab_rails['gitlab_protocol'] = 'https'
        gitlab_rails['gitlab_https'] = false
    expose:
      - '80'
    ports:
      - '8081:80'
      - '2222:22'
    networks:
      - int
    volumes:
      - './config:/etc/gitlab'
      - './data:/var/opt/gitlab'
      - './logs:/var/log/gitlab'

networks:
  int:
    external: true

``` 

I tried stopping and restarting container but did not worked
