### ISSUE TITLE
求救：runsv not running错误

### ISSUE THREAD

**Issue by allipr** [zengxs/gitlab-arm64#65]
mac电脑m2芯片arm64架构，准备在docker上部署gitlab-ce，遇到一个问题：  
* execute【/opt/gitlab/bin/gitlab-ctl start postgresql】 action run
      【execute】 fail: redis: runsv not running
      【execute】 fail: redis: runsv not running
该问题是我使用docker compose绑定数据卷时出现的错误（gitlab启动不起来），不绑定数据卷不会出现该错误。
绑定数据卷的docker compose如下：
绑定数据卷的docker compose如下：
```yml
# 版本
version: "2.1"
# 服务
services:
  # 服务名
  gitlab-ce-ser:
    # 镜像 macOS arm64芯片
    image: "yrzr/gitlab-ce-arm64v8:latest"
    # image: "gitlab/gitlab-ce:latest"
    # 容器名
    container_name: "gitlab-ce"
    # 重启策略 失败一直重启
    restart: always
    hostname: "127.0.0.1"
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        # external_url 'https://gitlab.example.com'
        # Add any other gitlab.rb configuration here, each on its own line
    ports:
      - "9090:80"
      - "9043:443"
      - "9022:22"
    volumes:
      - type: bind
        source: ${GITLAB_HOME}/config
        target: /etc/gitlab
      - type: bind
        source: ${GITLAB_HOME}/logs
        target: /var/log/gitlab
      - type: bind
        source: ${GITLAB_HOME}/data
        target: /var/opt/gitlab
    shm_size: "256m"
```

不绑定数据卷的docker compose 注销掉数据卷相关行即可。

绑定数据卷时，数据卷绑定是正常的，就是一旦绑定数据卷就会报上面的错误，请老师指教。十分感谢！
