### ISSUE TITLE
Connection troubles

### ISSUE THREAD

**Issue by xavetar** [zengxs/gitlab-arm64#7]
All ports except 22 do not work. The connection is reset.

docker-compose.yml:

```
version: '3.6'
services:
  web:
    image: 'zengxs/gitlab:ee' # Also: "image: 'zengxs/gitlab:latest'" or "image: 'zengxs/gitlab:ce'"
    restart: always
    hostname: 'localhost'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://localhost'
        gitlab_rails['gitlab_shell_ssh_port'] = 2222
        # Add any other gitlab.rb configuration here, each on its own line
    ports:
      - "3000:80"
      - "3001:443"
      - "2222:22"
    volumes:
      - ./config:/etc/gitlab
      - ./logs:/var/log/gitlab
      - ./data:/var/opt/gitlab
    shm_size: '256m'
```

<img width="890" alt="1" src="https://github.com/zengxs/gitlab-arm64/assets/52722847/d238b76c-b85f-4764-8b77-95d4bde3d985">
